import { CompleteStartupData } from '@/types/startup';

export const campusBiteData: CompleteStartupData = {
  startup: {
    id: 'campusbite-ai',
    userId: 'demo-user-1',
    name: 'CampusBite AI',
    tagline: 'Predictive Campus Food Marketplace & Smart Meal Subscriptions',
    problem: 'College students struggle to find affordable, healthy, and convenient meals near campus. Mess food is monotonous, aggregators charge exorbitant delivery fees (often 40-50% on low order values), and local cooks lack digital predictability.',
    solution: 'An AI-powered hyper-local campus food marketplace connecting students with verified local kitchens, dorm cooks, and cloud kitchens. Utilizes batch order routing to campus pickup hubs for zero delivery fees and algorithmic meal subscription scheduling.',
    targetCustomer: 'College and university students aged 18–25 living in university dorms, hostels, and off-campus PGs in urban university clusters.',
    businessModel: 'Subscription meal passes (₹2,499/month for 30 meals) + 12% vendor commission on à la carte orders + student-sponsored brand drops.',
    location: 'Tier-1 & Tier-2 University Hubs (Bengaluru, Pune, Delhi NCR, Kota)',
    budget: '₹5,00,000',
    founderSkills: 'Full-stack software engineering, local campus ambassador network, basic operations management.',
    status: 'Validated',
    createdAt: '2026-09-18T10:30:00Z',
    updatedAt: '2026-10-04T15:20:00Z',
  },
  analysis: {
    validationScore: 78,
    breakdown: {
      problemStrength: 86,
      solutionStrength: 82,
      marketOpportunity: 80,
      competition: 64,
      businessModel: 76,
      scalability: 74,
      financialFeasibility: 79,
      executionRisk: 68,
    },
    summary: 'CampusBite AI addresses a genuine, recurring, and painful problem in dense university ecosystems. The batch-delivery and subscription model fundamentally fixes the high-CAC and low-basket-size unit economic trap of traditional aggregators like Zomato/Swiggy. However, kitchen quality control, student summer churn, and tight margins are primary execution risks.',
    strengths: [
      'High recurring retention rate due to daily essential meal demand (3x/day touchpoint).',
      'Batch hub delivery reduces per-order fulfillment cost from ₹45 to under ₹9.',
      'Strong viral organic distribution through campus ambassador networks and dorm word-of-mouth.',
      'Lower take rate (12%) compared to mainstream aggregators (25-30%) attracts top local homestyle caterers.',
    ],
    weaknesses: [
      'Seasonal churn: Student population drops by 70% during 2.5 months of semester breaks and summer vacations.',
      'Low willingness to pay premium prices; student average order value (AOV) is price-sensitive (₹70–₹120).',
      'Operational friction in food safety oversight across decentralized home kitchens and mess vendors.',
    ],
    opportunities: [
      'Expansion into late-night exam cram meal slots (11 PM – 3 AM) where demand is inelastic.',
      'Institutional tie-ups with university administrations seeking outsourced hostel dining management.',
      'B2B data monetization: anonymized FMCG brand trials and student snack sampling.',
    ],
    risks: [
      {
        id: 'risk-1',
        title: 'Customer acquisition cost may spike when scaling beyond the primary campus',
        severity: 'HIGH',
        category: 'Customer',
        explanation: 'The target market is crowded, and while campus ambassadors work on day one, expanding across diverse universities requires distinct hyper-local marketing playbooks.',
        evidence: 'Historical food tech startups faced a 3.4x CAC increase when moving from their initial home university to secondary cities.',
        recommendation: 'Establish a repeatable campus playbook with 50 guaranteed student pre-orders before launching any new university cluster.',
      },
      {
        id: 'risk-2',
        title: 'Food safety and vendor quality consistency liability',
        severity: 'HIGH',
        category: 'Execution',
        explanation: 'A single food poisoning incident from a partnered mess can ruin brand reputation across campus WhatsApp groups overnight.',
        evidence: 'Mess health complaints are the #1 driver of negative student reviews in collegiate food networks.',
        recommendation: 'Implement mandatory FSSAI verification, bi-weekly surprise kitchen hygiene audits, and a student review strike-policy.',
      },
      {
        id: 'risk-3',
        title: 'Aggregator retaliation with campus discounted passes',
        severity: 'MEDIUM',
        category: 'Competition',
        explanation: 'Deep-pocketed competitors like Swiggy or Zomato could launch subsidized campus subscription pilots if they detect localized traction loss.',
        evidence: 'Large players have repeatedly tested localized student discounts in major university corridors.',
        recommendation: 'Lock in exclusive long-term supply contracts with the top 5 highest-rated campus culinary vendors.',
      },
      {
        id: 'risk-4',
        title: 'Semester vacation revenue dry spell',
        severity: 'MEDIUM',
        category: 'Revenue',
        explanation: 'Colleges shut down for 60-75 days annually, which creates fixed-cost overhead without student subscription revenue.',
        evidence: 'Academic calendar seasonality leaves June-July and December at 25% of baseline run-rate.',
        recommendation: 'Pivot idle kitchen capacity to nearby tech parks or corporate PG meal subscriptions during holiday months.',
      },
    ],
    recommendations: [
      'Focus strictly on 2 high-density universities (minimum 8,000 hostelites each) to reach unit economic profitability before city expansion.',
      'Transition from on-demand delivery to scheduled batch slots (Lunch 12:30 PM & 1:30 PM, Dinner 8:00 PM & 9:00 PM).',
      'Bundle laundry or snack subscriptions to increase average monthly revenue per student.',
    ],
  },
  market: {
    tam: '₹28,500 Cr ($3.4B)',
    sam: '₹6,200 Cr ($750M)',
    som: '₹420 Cr ($50M)',
    tamValue: 28500,
    samValue: 6200,
    somValue: 420,
    currency: '₹',
    cagr: '17.8%',
    opportunityScore: 84,
    segments: [
      { name: 'Hostel Students (Subscribed Meals)', percentage: 48, value: '₹200 Cr' },
      { name: 'Off-campus PG Renters (On-demand + Dinner)', percentage: 32, value: '₹135 Cr' },
      { name: 'Day Scholars (Lunch & Evening Snacks)', percentage: 14, value: '₹60 Cr' },
      { name: 'University Faculty & Staff', percentage: 6, value: '₹25 Cr' },
    ],
    growthProjection: [
      { year: '2025', marketSize: 180, projectedShare: 1.2 },
      { year: '2026', marketSize: 240, projectedShare: 4.8 },
      { year: '2027', marketSize: 320, projectedShare: 12.5 },
      { year: '2028', marketSize: 420, projectedShare: 24.0 },
      { year: '2029', marketSize: 550, projectedShare: 38.0 },
    ],
    trends: [
      'Rapid growth of private university townships with enclosed campus residency rules.',
      'Student demand shifting from junk fast-food towards hygienic, home-style (Ghar jaisa) comfort food.',
      'Ubiquitous UPI micropayments enabling zero-friction daily or weekly subscription top-ups.',
      'Rising gig-student delivery culture where students earn pocket money delivering on-campus.',
    ],
    failedPredecessors: [
      {
        name: 'TinyOwl / Yumist (Demo Research Case)',
        whatTheyTried: 'Full-stack cloud kitchens delivering individual ₹90 on-demand meals with independent motorcycle couriers across entire cities.',
        whyFailed: 'High logistics cost per order (₹50+ delivery cost on a ₹90 order), huge kitchen capex, and uncontrollable food wastage.',
        lesson: 'Do not build standalone kitchens or deliver single orders long distances. Marketplace model + campus batch density is essential.',
        howToAvoid: 'CampusBite operates as an asset-light marketplace and delivers 30 meals per single drop at designated campus hostels.',
      },
      {
        name: 'SpoonJoy (Demo Research Case)',
        whatTheyTried: 'Weekly office lunch subscriptions with zero minimum commitments.',
        whyFailed: 'Unpredictable daily order fluctuations led to 28% daily food wastage and severe margin erosion.',
        lesson: 'Subscription schedules must be locked in by 9:00 PM the previous evening to guarantee zero inventory risk for partner vendors.',
        howToAvoid: 'Cut-off time architecture ensures kitchens only cook verified pre-paid quantities.',
      },
    ],
  },
  competitors: [
    {
      id: 'comp-1',
      name: 'Zomato / Swiggy',
      pricing: '₹150 - ₹350 / meal (High fees)',
      targetMarket: 'General public & affluent urbanites',
      strength: 'Massive brand recall, exhaustive restaurant selection, deep delivery fleet.',
      weakness: '₹40-₹60 delivery + packaging markup makes regular daily dining prohibitive for students.',
      differentiator: 'CampusBite charges zero delivery fee via batch drop and provides curated monthly subscription passes at ₹79/meal.',
      marketShare: 52,
      pricePoint: 8,
      featureCompleteness: 9,
    },
    {
      id: 'comp-2',
      name: 'Campus Canteens & Mess',
      pricing: '₹2,000 - ₹3,000 / month',
      targetMarket: 'Hostel residents',
      strength: 'Direct on-site presence, mandatory in some hostels, rock bottom cost.',
      weakness: 'Extremely poor taste, repetitive menu, zero accountability, unhygienic conditions.',
      differentiator: 'Flexible multi-vendor options where students can swap between North Indian, South Indian, and healthy diet providers.',
      marketShare: 35,
      pricePoint: 3,
      featureCompleteness: 3,
    },
    {
      id: 'comp-3',
      name: 'Local Dabba & Tiffin Vendors',
      pricing: '₹80 - ₹110 / meal',
      targetMarket: 'PG students & bachelors',
      strength: 'Homestyle cooking, warm personal relationship.',
      weakness: 'Cash/offline only, frequent delivery delays, no tracking, poor weekend availability.',
      differentiator: 'CampusBite digitizes these exact tiffin vendors, gives them automated orders and batch logistics.',
      marketShare: 13,
      pricePoint: 4,
      featureCompleteness: 4,
    },
  ],
  competitiveAdvantage: 'Hyper-local Batch Hub Network: By aggregating 40-60 meals into single drop-off points at hostel gates, CampusBite slashes fulfillment cost by 80%, enabling restaurant-quality meals at mess prices while providing local vendors guaranteed volume.',
  swot: {
    strengths: [
      { id: 's-1', text: 'Hyper-local operational density around university campuses.', impact: 'High', suggestedAction: 'Double down on exclusive hostel distribution rights.' },
      { id: 's-2', text: 'Asset-light marketplace with verified home kitchens & mess vendors.', impact: 'High', suggestedAction: 'Maintain strict hygiene ratings to build student trust.' },
      { id: 's-3', text: 'High retention: 4.2 orders per active user per week.', impact: 'Medium', suggestedAction: 'Introduce loyalty points for exam-week study snacks.' },
      { id: 's-4', text: 'Sub-₹10 logistics cost per order via centralized batch drops.', impact: 'High', suggestedAction: 'Standardize 15-minute delivery window at hostel pickup zones.' },
    ],
    weaknesses: [
      { id: 'w-1', text: 'Semester break seasonality (2.5 months low utilization).', impact: 'High', suggestedAction: 'Diversify to nearby commercial corridors & tech parks during vacations.' },
      { id: 'w-2', text: 'Low basket size requires high order volume to cover fixed overheads.', impact: 'High', suggestedAction: 'Upsell beverages, dessert cups, and late-night snacks.' },
      { id: 'w-3', text: 'Initial brand dependency on student campus ambassadors.', impact: 'Medium', suggestedAction: 'Create institutional alumni co-sign programs.' },
    ],
    opportunities: [
      { id: 'o-1', text: 'Late-night hunger delivery (11:00 PM to 3:30 AM).', impact: 'High', suggestedAction: 'Partner with 2 dedicated night-shift cloud kitchens per campus.' },
      { id: 'o-2', text: 'Exclusive university administrative partnership for meal vouchers.', impact: 'Medium', suggestedAction: 'Pitch college registrars as an outsourced quality dining partner.' },
      { id: 'o-3', text: 'Branded FMCG sampling (Nestle, Red Bull, Paper Boat) inside meal boxes.', impact: 'Medium', suggestedAction: 'Create a B2B sampling media kit for student demographic access.' },
    ],
    threats: [
      { id: 't-1', text: 'Hostel warden regulations restricting outside delivery personnel.', impact: 'High', suggestedAction: 'Appoint student delivery captains living inside the same hostel.' },
      { id: 't-2', text: 'Price wars from subsidized aggregator student membership trials.', impact: 'Medium', suggestedAction: 'Focus on homestyle non-commercial food aggregators cannot replicate.' },
      { id: 't-3', text: 'Food safety incident at vendor kitchen affecting brand reputation.', impact: 'High', suggestedAction: 'Implement bi-monthly third-party swab tests and zero-tolerance delisting.' },
    ],
    aiSummary: 'CampusBite possesses an unbeatable unit-economics advantage through hostel batch fulfillment. Its biggest vulnerability is academic calendar seasonality and hostel entry restrictions, both of which can be mitigated using student resident delivery captains and vacation PG expansion.',
    strategicActions: [
      'Launch "Campus Captain" program: Pay hostel students ₹200/day to receive and distribute batch drops inside hostel gates.',
      'Lock in prepaid semester subscriptions with a 15% discount before the academic year starts.',
      'Deploy IoT temperature-monitored delivery totes to ensure hot food arrival at campus gates.',
    ],
  },
  personas: [
    {
      id: 'persona-1',
      name: 'Priya Sharma',
      role: 'College Student (3rd Year Computer Science)',
      age: 21,
      location: 'Dormitory, Bengaluru Tech Campus',
      income: '₹7,500 / month allowance',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      painPoints: [
        'College mess food is oily and repetitive.',
        'Zomato delivery fee (₹50) often exceeds 50% of the food item price.',
        'No reliable healthy breakfast options before 8:30 AM lectures.',
      ],
      goals: [
        'Eat wholesome, homestyle food for under ₹90 per meal.',
        'Quick pickup between classes without waiting 45 minutes.',
        'Predictable monthly food spending within monthly pocket money.',
      ],
      buyingBehavior: 'Orders online 4x/week, relies heavily on hostel group chats for food recommendations, pays exclusively via UPI.',
      budget: '₹2,500 – ₹3,200 / month on outside meals',
      techAdoption: 'Early Adopter',
      quote: 'If you can give me hot, healthy meals delivered to my hostel gate for ₹80 with no hidden fee, I will delete every other food app.',
    },
    {
      id: 'persona-2',
      name: 'Rahul Verma',
      role: 'Postgrad Student & Teaching Assistant',
      age: 24,
      location: 'Shared Flat near University, Pune',
      income: '₹22,000 / month stipend',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      painPoints: [
        'Cooking after 10 hours in lab is exhausting.',
        'Local tiffin services are irregular and stop delivery without warning.',
        'High protein options are either expensive or poor quality.',
      ],
      goals: [
        'Consistent lunch & dinner delivery with guaranteed delivery by 8:30 PM.',
        'Customizable nutrition (e.g. extra paneer/eggs or low-carb options).',
        'Easy pause and resume when traveling home for weekends.',
      ],
      buyingBehavior: 'Prefers automated weekly subscriptions so he never has to think about ordering every evening.',
      budget: '₹4,500 – ₹5,500 / month',
      techAdoption: 'Pragmatist',
      quote: 'I want a meal subscription that works like Netflix: set it, forget it, and pause it whenever I am away.',
    },
    {
      id: 'persona-3',
      name: 'Suresh Patil',
      role: 'Local Mess & Homestyle Cloud Kitchen Owner',
      age: 46,
      location: '1km from University Main Gate',
      income: '₹65,000 / month net',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
      painPoints: [
        'Major food delivery apps take 28% commission and delay settlements by 10 days.',
        'Food preparation wastage occurs when student walk-ins fluctuate unpredictably.',
        'Cannot afford expensive digital advertising or packaging.',
      ],
      goals: [
        'Guaranteed daily order volumes so all ingredients are purchased in bulk.',
        'Fair take rates (under 15%) and next-day UPI payouts.',
        'Simple interface without complicated tablets or POS systems.',
      ],
      buyingBehavior: 'Values relationships and guaranteed volume over speculative surges; tech-hesitant but active on WhatsApp.',
      budget: 'Willing to pay 10-12% commission for guaranteed 50+ meals/day',
      techAdoption: 'Conservative',
      quote: 'If you can tell me at 9 AM that exactly 75 students will eat my thali at 1 PM, I will gladly give you my best price.',
    },
  ],
  interviews: {
    'persona-1': {
      messages: [
        { id: 'm-1', sender: 'user', text: 'Hey Priya! If CampusBite offers daily hot homestyle thalis delivered right to your hostel gate for ₹79 with zero delivery charges, would you subscribe?', timestamp: '10:02 AM' },
        { id: 'm-2', sender: 'customer', text: 'Honestly, ₹79 sounds amazing compared to Swiggy, but only if the food is clean and not oily like the campus mess. Can I choose what comes in the meal, or is it a fixed menu?', timestamp: '10:03 AM' },
        { id: 'm-3', sender: 'user', text: 'You can choose between 3 daily curated options (Homestyle North, South, and Fitness Bowl) every morning before 10 AM, and pause whenever you go out.', timestamp: '10:04 AM' },
        { id: 'm-4', sender: 'customer', text: 'The pause feature is a game-changer! If I can pause for weekends when I go home to Mysore, I would easily pay ₹2,500 per month upfront.', timestamp: '10:05 AM' },
      ],
      evaluation: {
        interestScore: 92,
        painPointScore: 88,
        willingnessToPay: '₹2,400 - ₹2,700 / month prepaid',
        objections: [
          'Fear of repetitive menus after 2 weeks of subscription.',
          'Concerns about delivery delays during lunch break between consecutive lectures.',
          'Wants easy weekend pause without customer support hassle.',
        ],
        keyInsights: [
          'Zero delivery fee is the single biggest conversion hook for college hostelites.',
          'A flexible pause-and-resume feature is mandatory to prevent churn when students leave campus.',
          'Hostel gate delivery is 10x more valuable than room delivery because security blocks outsiders anyway.',
        ],
        recommendedChanges: [
          'Provide a 7-day revolving menu with guest kitchen rotations on Fridays.',
          'Implement a 10-minute pickup window countdown with WhatsApp notification.',
        ],
      },
    },
  },
  investorReviews: [
    {
      id: 'inv-1',
      persona: 'Angel Investor',
      name: 'Rajat Verma',
      title: 'Founder & Angel Investor, ex-FoodTech Unicorn',
      firm: 'Campus Angels Syndicate',
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      verdict: 'Strong Interest',
      confidenceScore: 82,
      strengths: [
        'Batch drop logistics solves the fundamental unit economics failure of food delivery.',
        'High organic viral coefficient across tightly knit university dorms (K-factor > 1.4).',
        'Prepaid subscription generates negative working capital (cash upfront from students).',
      ],
      concerns: [
        'Can the founders defend against localized copycats at other universities?',
        'Vendor quality consistency as volume expands beyond 20 kitchens.',
      ],
      questions: [
        'What is your target customer acquisition cost per student, and how many meals until payback?',
        'How do you manage supply side quality when demand spikes during exam weeks?',
      ],
      recommendation: 'Double down on campus density before spreading across multiple cities. Prove 1,000 daily active subscribers on a single campus.',
    },
    {
      id: 'inv-2',
      persona: 'Venture Capitalist',
      name: 'Ananya Deshmukh',
      title: 'Partner',
      firm: 'Nexus Frontier Ventures',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      verdict: 'Interested with Conditions',
      confidenceScore: 74,
      strengths: [
        'Large addressable market across India’s 40 million higher education students.',
        'Potential to expand from food into laundry, stationery, and micro-commerce.',
      ],
      concerns: [
        'Student purchasing power is low, capping AOV and long-term gross margins.',
        '2.5 months of annual revenue dormancy due to university vacations.',
      ],
      questions: [
        'How will you retain kitchen partners during summer breaks when students go home?',
        'What is your gross margin profile after payment gateway, packaging, and campus captain fees?',
      ],
      recommendation: 'Develop an off-season corporate or PG strategy to keep kitchen partners active throughout the calendar year.',
    },
    {
      id: 'inv-3',
      persona: 'Bank Loan Officer',
      name: 'S. Ramanathan',
      title: 'Chief SME Credit Manager',
      firm: 'State Bank MSME Cell',
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
      verdict: 'Needs Traction',
      confidenceScore: 65,
      strengths: [
        'Asset-light model requires minimal heavy machinery or leased real estate.',
        'Digital UPI cash flow allows transparent tracking of receivables.',
      ],
      concerns: [
        'No collateralized physical assets to pledge against term loans.',
        'High dependence on student subscriptions with short 3-month commitments.',
      ],
      questions: [
        'What is your debt service coverage ratio based on verified 6-month bank statements?',
        'Do you have personal founder guarantees or institutional university MoUs?',
      ],
      recommendation: 'Bootstrap with revenue-based financing or incubator grants before seeking commercial bank credit lines.',
    },
    {
      id: 'inv-4',
      persona: 'Shark Tank Judge',
      name: 'Vikramaditya Singhania',
      title: 'Managing Director & Retail Mogul',
      firm: 'Singhania Consumer Brands',
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
      verdict: 'Interested with Conditions',
      confidenceScore: 76,
      strengths: [
        'Real, undeniable pain point: mess food is hated by 95% of students in every college in India.',
        'Batch drop model is brilliant and solves the Swiggy/Zomato unit economics bottleneck.',
      ],
      concerns: [
        'Execution is brutal. If 50 meals arrive cold at 1:15 PM, students will revolt on Twitter and Instagram.',
        'Can you defend against food poisoning claims?',
      ],
      questions: [
        'What is your exact profit per meal box at ₹79 retail price?',
        'How fast can you take over 5 colleges in Bangalore without hiring full-time managers?',
      ],
      recommendation: 'Standardize thermal packaging and lock in university hostel student heads as exclusive partners. I would invest ₹40 Lakh for 10% equity once 3 campuses are profitable.',
    },
  ],
  investorConfidenceScore: 74,
  businessModel: {
    keyPartners: [
      'Verified local mess owners and homestyle cloud kitchens.',
      'Student Campus Ambassadors & Hostel Resident Captains.',
      'FSSAI food safety testing labs and hygiene certifiers.',
      'Thermal insulated delivery bag & eco-friendly packaging manufacturers.',
      'UPI payment gateways (Razorpay / Cashfree) with recurring autopay.',
    ],
    keyActivities: [
      'Demand prediction and algorithmic kitchen meal allocation by 9:00 PM nightly.',
      'Hostel batch route optimization and student pickup coordination.',
      'Bi-weekly kitchen hygiene checks and food quality audits.',
      'Campus marketing, referral contests, and orientation week onboarding.',
    ],
    valuePropositions: [
      'For Students: Hygienic, delicious homestyle meals at ₹79 with zero delivery charges and flexible pause.',
      'For Kitchens: 40-100 guaranteed daily pre-orders with next-day payouts and zero advertising overhead.',
      'For Colleges: Reduced student complaints about dining hall food without administrative headaches.',
    ],
    customerRelationships: [
      'Automated daily menu push via WhatsApp bot & Mobile App.',
      'Dedicated Campus Captain for real-time resolution at hostel gates.',
      'Transparent community rating board for every participating kitchen.',
    ],
    customerSegments: [
      'Undergraduate hostel students living in non-cooking dorms (Core segment).',
      'PG tenants and graduate scholars in surrounding university lanes.',
      'University non-teaching staff and day scholars wanting affordable lunch.',
    ],
    keyResources: [
      'Proprietary batch-dispatch and meal scheduling software.',
      'Campus Captain network with campus security access.',
      'Curated network of audited, verified neighborhood cooks.',
    ],
    channels: [
      'Direct mobile web app and PWA.',
      'Hostel WhatsApp and Telegram study groups.',
      'Campus orientation event sponsorships and poster QR codes.',
      'Peer-to-peer student referral bonuses (Free meal for both).',
    ],
    costStructure: [
      'Food acquisition cost paid to partner kitchens (₹52 - ₹56 per meal).',
      'Campus Captain batch delivery incentive (₹6 - ₹8 per order drop).',
      'Eco-friendly compostable packaging & thermal bag depreciation (₹4 per meal).',
      'Payment gateway fees (1.8%) and cloud infrastructure hosting.',
    ],
    revenueStreams: [
      'Student Monthly & Weekly Subscription Passes (78% of gross revenue).',
      'A la carte orders with 12% marketplace commission (14% of revenue).',
      'FMCG brand sampling and university campus advertising drops (8% of revenue).',
    ],
    recommendedModel: {
      type: 'Hybrid Recurring Subscription + High-Margin Ancillary Add-ons',
      why: 'Subscriptions eliminate demand volatility, allowing kitchens to buy groceries in bulk and student order retention to remain above 75% month-on-month.',
      expectedMonthlyRevenue: '₹3,55,500 across 450 active subscribers per campus',
      advantages: [
        'Predictable cash flow upfront at the beginning of each billing cycle.',
        'Zero kitchen food inventory waste, passing savings directly to student pricing.',
        'High switching costs once students get into a routine.',
      ],
      risks: [
        'Subscriber fatigue if menu variety is not refreshed monthly.',
        'Vacation drop-offs require flexible pause handling without refund friction.',
      ],
    },
  },
  financials: {
    currency: '₹',
    initialInvestment: 500000,
    monthlyOperatingCost: 120000,
    employees: 3,
    marketingCost: 25000,
    technologyCost: 12000,
    pricePerCustomer: 2499,
    expectedCustomers: 450,
    monthlyRevenue: 1124550,
    monthlyExpenses: 894000,
    grossProfit: 230550,
    burnRate: 0,
    breakEvenCustomers: 260,
    runwayMonths: 18.5,
    projections: [
      { month: 'Month 1', revenue: 250000, expenses: 310000, profit: -60000, customers: 100 },
      { month: 'Month 2', revenue: 450000, expenses: 480000, profit: -30000, customers: 180 },
      { month: 'Month 3', revenue: 700000, expenses: 690000, profit: 10000, customers: 280 },
      { month: 'Month 4', revenue: 950000, expenses: 840000, profit: 110000, customers: 380 },
      { month: 'Month 5', revenue: 1125000, expenses: 894000, profit: 231000, customers: 450 },
      { month: 'Month 6', revenue: 1375000, expenses: 1040000, profit: 335000, customers: 550 },
      { month: 'Month 7', revenue: 1625000, expenses: 1190000, profit: 435000, customers: 650 },
      { month: 'Month 8', revenue: 1900000, expenses: 1350000, profit: 550000, customers: 760 },
      { month: 'Month 9', revenue: 2200000, expenses: 1520000, profit: 680000, customers: 880 },
      { month: 'Month 10', revenue: 2500000, expenses: 1700000, profit: 800000, customers: 1000 },
      { month: 'Month 11', revenue: 2875000, expenses: 1910000, profit: 965000, customers: 1150 },
      { month: 'Month 12', revenue: 3250000, expenses: 2120000, profit: 1130000, customers: 1300 },
    ],
  },
  techStack: {
    frontend: {
      name: 'Next.js 16 + React 19 + Tailwind CSS',
      category: 'Frontend & PWA',
      reason: 'Ultra-fast server rendering, seamless mobile responsive PWA capabilities, and instantaneous page transitions on poor campus Wi-Fi networks.',
      pros: ['Sub-second page load times', 'Built-in SEO & OpenGraph card sharing', 'Zero app-store download friction'],
    },
    backend: {
      name: 'Next.js App Router API + Python FastAPI Service',
      category: 'Backend Architecture',
      reason: 'Lightweight TypeScript API handlers for business logic with a high-throughput Python FastAPI microservice for batch routing heuristics and ML demand prediction.',
      pros: ['Fast development cycle', 'Strong typing with Zod & Pydantic', 'Async performance for batch calculations'],
    },
    database: {
      name: 'Supabase PostgreSQL',
      category: 'Primary Database',
      reason: 'Relational integrity for orders, financial ledgering, subscriptions, and vendor audits with Row Level Security built-in.',
      pros: ['ACID transactional reliability', 'Native JSONB support for flexible menus', 'Managed automated backups'],
    },
    cloud: {
      name: 'Vercel Edge Network + Supabase Cloud',
      category: 'Cloud Infrastructure',
      reason: 'Global CDN edge nodes with zero DevOps overhead, allowing founders to focus strictly on campus operations.',
      pros: ['Instant previews & zero server provisioning', 'Auto-scaling for 12:30 PM order spikes', 'Generous free tier'],
    },
    auth: {
      name: 'Supabase Auth (SMS OTP + Student Email SSO)',
      category: 'Identity & Authentication',
      reason: 'Frictionless phone number login for quick campus orders plus .ac.in / .edu email verification for student discounts.',
      pros: ['JWT token session persistence', 'Built-in RLS policies', 'Instant OTP verification'],
    },
    aiModel: {
      name: 'OpenAI GPT-4o / Google Gemini 1.5 Pro',
      category: 'AI Engine',
      reason: 'Analyzes dietary preferences, generates personalized weekly nutrition meal plans, and powers automated kitchen order allocation.',
      pros: ['Structured JSON mode output', 'Multi-lingual support for regional cooks', 'Low latency response times'],
    },
    vectorDb: {
      name: 'Supabase pgvector',
      category: 'Vector Database & Memory',
      reason: 'Stores meal nutrition embeddings, student preference profiles, and past review sentiment vectors directly inside PostgreSQL.',
      pros: ['No separate database infrastructure required', 'Fast cosine similarity lookups', 'Integrated with Supabase RLS'],
    },
    apis: {
      name: 'Tavily API & Razorpay Route API',
      category: 'External APIs',
      reason: 'Live market research queries on competitive food trends combined with automated split escrow payouts to kitchen partners.',
      pros: ['Automated vendor commissions', 'Real-time Web Search capabilities', 'Reliable UPI webhook handling'],
    },
    analytics: {
      name: 'PostHog & Recharts',
      category: 'Product Analytics & Visualization',
      reason: 'Privacy-friendly user funnel tracking for subscription drop-offs and real-time dashboard data visualization.',
      pros: ['Funnel conversion tracking', 'Cohort retention analysis', 'Clean lightweight charts'],
    },
    storage: {
      name: 'Supabase Storage (S3-compatible)',
      category: 'File & Media Storage',
      reason: 'Secure hosting of kitchen FSSAI hygiene certificates, food preparation photos, and PDF investor reports.',
      pros: ['CDN image caching & transformation', 'Direct signed upload URLs', 'Encrypted bucket security'],
    },
  },
  roadmap: [
    {
      phaseNumber: 1,
      phaseTitle: 'Phase 1: Hyper-Local Validation & Partner Onboarding',
      duration: 'Weeks 1 – 4',
      milestones: [
        { id: 'm1-1', task: 'Survey 250 students across 3 campus hostels regarding dining dissatisfaction and price sensitivity.', priority: 'HIGH', estimatedDuration: '10 days', dependencies: 'None', status: 'Completed' },
        { id: 'm1-2', task: 'Audit and sign letters of intent (LOI) with 5 local homestyle mess kitchens with FSSAI verification.', priority: 'HIGH', estimatedDuration: '14 days', dependencies: 'Student survey', status: 'Completed' },
        { id: 'm1-3', task: 'Launch pilot WhatsApp concierge ordering group with 40 students to test batch delivery mechanics.', priority: 'MEDIUM', estimatedDuration: '7 days', dependencies: 'Kitchen LOIs', status: 'Completed' },
      ],
    },
    {
      phaseNumber: 2,
      phaseTitle: 'Phase 2: MVP Development & Batch Routing Engine',
      duration: 'Weeks 5 – 8',
      milestones: [
        { id: 'm2-1', task: 'Deploy responsive Next.js web application with student authentication and UPI subscription checkout.', priority: 'HIGH', estimatedDuration: '18 days', dependencies: 'Phase 1 insights', status: 'In Progress' },
        { id: 'm2-2', task: 'Develop Vendor Portal for daily morning dish selection and automated portion counting.', priority: 'HIGH', estimatedDuration: '14 days', dependencies: 'Core DB schema', status: 'In Progress' },
        { id: 'm2-3', task: 'Establish campus pickup hubs at Hostel 1, 2, and 4 gates with thermal tote storage.', priority: 'MEDIUM', estimatedDuration: '7 days', dependencies: 'Hostel permissions', status: 'Not Started' },
      ],
    },
    {
      phaseNumber: 3,
      phaseTitle: 'Phase 3: Beta Campus Launch & Retention Optimization',
      duration: 'Weeks 9 – 12',
      milestones: [
        { id: 'm3-1', task: 'Onboard 150 paid subscribers on 30-day passes at University #1.', priority: 'HIGH', estimatedDuration: '30 days', dependencies: 'MVP release', status: 'Not Started' },
        { id: 'm3-2', task: 'Deploy automated pause/resume feature and measure Week 4 retention cohort.', priority: 'HIGH', estimatedDuration: '10 days', dependencies: 'Beta launch', status: 'Not Started' },
        { id: 'm3-3', task: 'Implement student campus captain reward system for delivery coordination.', priority: 'MEDIUM', estimatedDuration: '8 days', dependencies: 'Subscribers onboarded', status: 'Not Started' },
      ],
    },
    {
      phaseNumber: 4,
      phaseTitle: 'Phase 4: Multi-Campus Expansion & Late-Night Slot',
      duration: 'Months 4 – 6',
      milestones: [
        { id: 'm4-1', task: 'Launch late-night snack & cram meal delivery (11:00 PM – 3:00 AM) to boost high-margin revenue.', priority: 'HIGH', estimatedDuration: '21 days', dependencies: 'Daytime stability', status: 'Not Started' },
        { id: 'm4-2', task: 'Expand playbook to 2 adjacent university campuses in Pune/Bangalore corridor.', priority: 'HIGH', estimatedDuration: '45 days', dependencies: 'Campus 1 breakeven', status: 'Not Started' },
        { id: 'm4-3', task: 'Introduce B2B brand sampling partnerships inside lunch meal packaging.', priority: 'LOW', estimatedDuration: '14 days', dependencies: '500+ daily volume', status: 'Not Started' },
      ],
    },
    {
      phaseNumber: 5,
      phaseTitle: 'Phase 5: Institutional Integration & Seed Fundraising',
      duration: 'Months 7 – 9',
      milestones: [
        { id: 'm5-1', task: 'Reach ₹25 Lakhs monthly GMV with positive contribution margin on all deliveries.', priority: 'HIGH', estimatedDuration: '60 days', dependencies: 'Multi-campus launch', status: 'Not Started' },
        { id: 'm5-2', task: 'Sign official dining partnership with 2 private university administrations.', priority: 'MEDIUM', estimatedDuration: '45 days', dependencies: 'Clean health audit track record', status: 'Not Started' },
        { id: 'm5-3', task: 'Prepare institutional data room and raise $500K Seed round for 15-campus rollout.', priority: 'HIGH', estimatedDuration: '45 days', dependencies: 'Unit economics verified', status: 'Not Started' },
      ],
    },
  ],
  readiness: {
    overallScore: 74,
    categories: [
      { name: 'Problem Severity', score: 88, weight: '12%', comment: 'Compelling, daily recurring student frustration with strong willingness to switch.' },
      { name: 'Market Size & Timing', score: 82, weight: '10%', comment: 'India’s higher education market is expanding with enclosed campus townships.' },
      { name: 'Unit Economics Viability', score: 79, weight: '15%', comment: 'Batch delivery creates positive gross margin per drop where traditional apps lose money.' },
      { name: 'Competitive Moat', score: 62, weight: '12%', comment: 'Low technical barrier to entry; moat relies heavily on hyper-local vendor contracts & ambassador loyalty.' },
      { name: 'Scalability Potential', score: 71, weight: '10%', comment: 'High density per college, but scaling requires repeating the campus playbook college by college.' },
      { name: 'Traction & Validation', score: 75, weight: '15%', comment: 'Survey and pilot data are positive; needs 60 consecutive days of paid cohort retention.' },
      { name: 'Business Model', score: 77, weight: '10%', comment: 'Prepaid subscriptions provide working capital stability and predictable daily prep.' },
      { name: 'Regulatory & Food Safety', score: 65, weight: '8%', comment: 'FSSAI compliance and vendor hygiene enforcement need strict standard operating procedures.' },
      { name: 'Financial Feasibility', score: 78, weight: '8%', comment: 'Lean capital requirement: initial ₹5,00,000 is sufficient to reach breakeven on 2 campuses.' },
    ],
    topReasonsToInvest: [
      'Disrupts food delivery unit economics: Batch drops reduce fulfillment cost by over 80% compared to traditional on-demand couriers.',
      'Extreme daily customer engagement: Food is an essential 3x/day touchpoint, driving natural referral loops and zero customer churn during semesters.',
      'Negative working capital cycle: Students prepay subscriptions at the beginning of the month, funding operations before supplier payouts.',
    ],
    topReasonsToReject: [
      'Academic calendar seasonality causes 2.5 months of sharp revenue contraction each summer and winter break.',
      'Defensibility risk: If a major food tech aggregator discounts student passes in top campuses, margins could come under severe pressure.',
      'Execution fragility: Quality failure or food poisoning from a single rogue vendor can quickly propagate across campus social media.',
    ],
    improvementRoadmap: [
      'Secure formal written agreements with campus hostel resident councils to solidify the distribution moat.',
      'Launch corporate PG pilot in July to generate revenue during university summer vacations.',
      'Implement IoT temperature sensors on batch delivery totes to prove hygiene and food freshness to parents and investors.',
    ],
    founderReadiness: {
      overallScore: 81,
      technicalSkills: 88,
      businessKnowledge: 76,
      marketingAcumen: 84,
      financialPreparation: 75,
      teamStrength: 78,
      leadership: 82,
      executionCapability: 85,
      recommendations: [
        'Onboard a dedicated Operations Co-Founder or Lead with prior experience in cloud kitchen management or FMCG supply chains.',
        'Build a standardized financial model with sensitivity analysis for 10%, 20%, and 30% vacation drop-offs.',
        'Establish advisory relationships with experienced food tech founders who have scaled collegiate marketplaces.',
      ],
    },
  },
  pivots: [
    {
      id: 'pivot-1',
      title: 'Hostel Mess Operating System (SaaS Model)',
      description: 'Pivot from running consumer food deliveries to providing an enterprise management SaaS for existing college canteens and caterers (inventory forecasting, automated student billing, menu feedback).',
      marketPotential: 'High',
      difficulty: 'Medium',
      investment: '₹3,00,000',
      risk: 'Low',
      revenuePotential: '₹25,000 / month per university canteen',
      rationale: 'Eliminates logistics liability and food safety risk while maintaining high recurring software margins (85%+ gross margin).',
    },
    {
      id: 'pivot-2',
      title: 'Late-Night Dark Store for Exam Corridors',
      description: 'Focus exclusively on high-margin late night delivery (10 PM to 4 AM) stocking hot noodles, energy drinks, snacks, and stationery directly from a small rented room next to campus.',
      marketPotential: 'Moderate',
      difficulty: 'Low',
      investment: '₹2,50,000',
      risk: 'Medium',
      revenuePotential: '₹1,50,000 / month gross profit',
      rationale: 'Inelastic price demand during night hours allows 40% gross margins and avoids daytime aggregator competition.',
    },
    {
      id: 'pivot-3',
      title: 'Corporate PG & Tech Park Meal Subscriptions',
      description: 'Re-target the subscription meal engine to young software engineers and junior corporate staff living in Paying Guest (PG) accommodations in IT corridors.',
      marketPotential: 'Very High',
      difficulty: 'High',
      investment: '₹8,00,000',
      risk: 'Medium',
      revenuePotential: '₹4,500 / month per subscriber (2x student ticket size)',
      rationale: 'Year-round stability without college vacations and 2x higher willingness to pay.',
    },
  ],
  versions: [
    {
      id: 'v-1',
      versionNumber: 1,
      date: '2026-09-18',
      score: 64,
      changes: 'Initial concept: On-demand student food delivery with bicycle couriers.',
      reason: 'AI Devil’s Advocate revealed that individual on-demand deliveries yielded negative unit economics (-₹32 per delivery).',
    },
    {
      id: 'v-2',
      versionNumber: 2,
      date: '2026-09-28',
      score: 72,
      changes: 'Switched to scheduled batch drop hubs at hostel gates + monthly meal subscription passes.',
      reason: 'Reduced fulfillment cost from ₹42 to under ₹9, significantly boosting financial feasibility and unit margins.',
    },
    {
      id: 'v-3',
      versionNumber: 3,
      date: '2026-10-04',
      score: 78,
      changes: 'Added summer corporate PG pivot, FSSAI quality audit protocols, and Campus Captain incentive network.',
      reason: 'Addressed investor concerns regarding university summer vacation churn and hostel entry access.',
    },
  ],
  messages: [
    {
      id: 'msg-1',
      sender: 'assistant',
      text: 'Good morning Founder! I am your AI Co-Founder for CampusBite AI. I’ve analyzed your current validation score of 78/100. Your batch delivery model is rock-solid, but our biggest immediate hurdle is vacation churn and campus access permissions. How would you like to tackle these today?',
      timestamp: '09:30 AM',
    },
    {
      id: 'msg-2',
      sender: 'user',
      text: 'What should be my #1 priority before launching next week?',
      timestamp: '09:32 AM',
    },
    {
      id: 'msg-3',
      sender: 'assistant',
      text: 'Your #1 priority is locking down 3 "Campus Captains" inside the largest hostel. Without student insiders who have hostel biometric access, delivery boys will be stopped at the outer security gate, causing 25-minute delays and cold food complaints. Get these 3 captains onboarded and give them free meals for 2 weeks.',
      timestamp: '09:33 AM',
    },
  ],
};

export const greenCartData: CompleteStartupData = {
  ...campusBiteData,
  startup: {
    id: 'greencart',
    userId: 'demo-user-1',
    name: 'GreenCart',
    tagline: 'Zero-Waste Circular Grocery Delivery & Refill Network',
    problem: 'Urban households generate over 12kg of single-use plastic grocery packaging every month. Consumers want to live sustainably, but eco-friendly alternatives are either 3x more expensive or require inconvenient bulk shopping trips.',
    solution: 'A smart refill grocery delivery platform that delivers organic pantry staples in standardized, sanitizable stainless steel containers. On the next delivery, empty containers are collected, washed, and reused in a circular loop.',
    targetCustomer: 'Eco-conscious urban families and young professionals aged 25–42 living in high-rise gated communities in Tier-1 cities.',
    businessModel: 'Direct-to-consumer grocery sales with 26% product gross margin + monthly green membership (₹199/month for unlimited refills and priority slots).',
    location: 'Bengaluru, Mumbai, Hyderabad',
    budget: '₹12,00,000',
    founderSkills: 'Supply chain operations, organic sourcing, product design.',
    status: 'Validated',
    createdAt: '2026-08-10T12:00:00Z',
    updatedAt: '2026-10-02T11:45:00Z',
  },
  analysis: {
    validationScore: 84,
    breakdown: {
      problemStrength: 82,
      solutionStrength: 88,
      marketOpportunity: 85,
      competition: 78,
      businessModel: 84,
      scalability: 81,
      financialFeasibility: 85,
      executionRisk: 79,
    },
    summary: 'GreenCart addresses a rapidly intensifying climate issue with an elegant circular logistics loop. By focusing on gated communities, container retrieval density is high, overcoming the traditional friction of reverse logistics.',
    strengths: [
      '84% monthly retention among gated community beta households.',
      'High basket size (Average Order Value ₹1,650 vs ₹450 for quick commerce).',
      'Strong ESG alignment attracting premium sustainability-minded customers.',
    ],
    weaknesses: [
      'Container capex (₹180 per stainless steel container set) increases initial working capital requirements.',
      'Requires strict industrial dishwashing and sterilization facilities to satisfy food safety norms.',
    ],
    opportunities: [
      'Corporate ESG wellness partnerships providing employee subsidized grocery credits.',
      'Private label expansion into organic lentils, cold-pressed oils, and spices.',
    ],
    risks: [
      {
        id: 'gc-r1',
        title: 'Container loss and hoarding by households',
        severity: 'MEDIUM',
        category: 'Customer',
        explanation: 'Customers may forget to return empty containers or repurpose them for kitchen storage.',
        evidence: 'Earlier circular packaging trials experienced a 14% container attrition rate in non-gated neighborhoods.',
        recommendation: 'Implement an automated refundable container deposit (₹50/container) credited instantly upon pickup.',
      },
    ],
    recommendations: [
      'Concentrate rollout inside 15 major gated apartment complexes (minimum 500 flats each).',
      'Offer automated weekly pantry replenishment subscriptions for staple grains and oils.',
    ],
  },
};

export const skillBridgeData: CompleteStartupData = {
  ...campusBiteData,
  startup: {
    id: 'skillbridge-ai',
    userId: 'demo-user-1',
    name: 'SkillBridge AI',
    tagline: 'AI-Driven Vocational Upskilling & Guaranteed Freelance Matching',
    problem: 'Tier-2 and Tier-3 college graduates lack practical job-ready skills (AI prompt engineering, modern cloud tools, data analytics). Traditional ed-tech courses charge ₹40,000+ with less than 8% verified job placement.',
    solution: 'An AI-guided micro-apprenticeship platform where students complete interactive, real-world corporate code repositories and get matched with international startups for paid freelance gigs.',
    targetCustomer: 'Engineering and polytechnic students from tier-2/3 institutes seeking global tech employment.',
    businessModel: 'Free practical training with 15% platform commission on earned freelance bounties + B2B employer recruitment fees.',
    location: 'Remote-first / India Pan-Country',
    budget: '₹3,50,000',
    founderSkills: 'AI engineering, developer relations, edtech curriculum.',
    status: 'Validated',
    createdAt: '2026-07-05T09:15:00Z',
    updatedAt: '2026-09-29T16:30:00Z',
  },
  analysis: {
    validationScore: 72,
    breakdown: {
      problemStrength: 89,
      solutionStrength: 75,
      marketOpportunity: 86,
      competition: 58,
      businessModel: 71,
      scalability: 82,
      financialFeasibility: 74,
      executionRisk: 61,
    },
    summary: 'SkillBridge AI targets the massive employability gap in emerging markets. Its pay-after-earning model breaks upfront student skepticism. The core challenge is sustaining high-quality international employer demand for junior talent.',
    strengths: [
      'Zero upfront fees creates massive student viral signups.',
      'Automated AI code review provides instant feedback without human instructor bottlenecks.',
    ],
    weaknesses: [
      'B2B employer acquisition is competitive against Upwork and specialized talent agencies.',
      'Student dropout rates during challenging technical modules.',
    ],
    opportunities: [
      'Global startups seeking cost-effective AI operations and prompt engineering talent.',
      'State government skill development subsidies and university accreditations.',
    ],
    risks: [
      {
        id: 'sb-r1',
        title: 'Platform disintermediation',
        severity: 'HIGH',
        category: 'Revenue',
        explanation: 'Students and hiring companies may transact directly off-platform after the first successful gig.',
        evidence: 'Freelance platforms consistently lose 20-30% of long-term billings to off-platform contracts.',
        recommendation: 'Provide automated tax invoicing, international payment compliance, and health insurance to incentivize staying on-platform.',
      },
    ],
    recommendations: [
      'Focus initial curriculum on "AI Workflow Automation" where demand currently outstrips supply.',
      'Introduce verified skill badges backed by automated code evaluation test suites.',
    ],
  },
};

export const allStartupsList = [
  campusBiteData.startup,
  greenCartData.startup,
  skillBridgeData.startup,
];

export const demoDatabase: Record<string, CompleteStartupData> = {
  'campusbite-ai': campusBiteData,
  'greencart': greenCartData,
  'skillbridge-ai': skillBridgeData,
};
