'use client';

import React, { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { getStoredStartups } from '@/lib/storage';
import { demoDatabase } from '@/lib/mockData';
import { CompleteStartupData } from '@/types/startup';
import { Sparkles, Download, Share2, FileText, Printer, CheckCircle2, ShieldCheck } from 'lucide-react';

function ReportsContent() {
  const searchParams = useSearchParams();
  const startupParam = searchParams.get('startup') || 'campusbite-ai';

  const [startups, setStartups] = useState<Record<string, CompleteStartupData>>({});
  const [selectedId, setSelectedId] = useState(startupParam);
  const [exporting, setExporting] = useState(false);
  const [shared, setShared] = useState(false);

  useEffect(() => {
    const loaded = getStoredStartups();
    setStartups(loaded);
  }, []);

  const data = startups[selectedId] || demoDatabase[selectedId] || demoDatabase['campusbite-ai'];
  if (!data) return null;

  const { startup, analysis, market, swot, businessModel, financials, techStack, readiness } = data;

  const handleExportPDF = () => {
    setExporting(true);
    setTimeout(() => {
      window.print();
      setExporting(false);
    }, 300);
  };

  const handleExportDOCX = () => {
    setExporting(true);
    const content = `STARTUPIQ EXECUTIVE STARTUP DOSSIER
Startup Name: ${startup.name}
Tagline: ${startup.tagline}
Validation Score: ${analysis.validationScore}/100
Investor Readiness: ${readiness.overallScore}/100

1. EXECUTIVE SUMMARY
${analysis.summary}

2. PROBLEM & SOLUTION
Problem: ${startup.problem}
Solution: ${startup.solution}
Target Customer: ${startup.targetCustomer}

3. MARKET ANALYSIS
TAM: ${market.tam} | SAM: ${market.sam} | SOM: ${market.som}
CAGR: ${market.cagr}

4. AI DEVIL'S ADVOCATE CRITICAL RISKS
${analysis.risks.map(r => `- [${r.severity}] ${r.title}: ${r.explanation}`).join('\n')}

5. FINANCIAL PLAN
Monthly Revenue: ${financials.monthlyRevenue}
Monthly Expenses: ${financials.monthlyExpenses}
Break-Even Customers: ${financials.breakEvenCustomers}

Report Generated by StartupIQ Platform.
`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${startup.name.toLowerCase().replace(/\s+/g, '-')}-dossier.txt`;
    link.click();
    setExporting(false);
  };

  const handleShare = () => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(window.location.href);
      setShared(true);
      setTimeout(() => setShared(false), 2000);
    }
  };

  return (
    <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 space-y-8 print:p-0 print:bg-white print:text-black">
      {/* Top Controls (Hidden on print) */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-6 print:hidden">
        <div>
          <span className="text-xs font-bold text-indigo-400 uppercase tracking-wider">
            Document Generation
          </span>
          <h1 className="text-3xl font-extrabold text-white">Executive Startup Dossier</h1>
          <p className="text-xs text-slate-400 mt-1">
            Export investor pitch reports with StartupIQ validation stamp.
          </p>
        </div>

        <div className="flex flex-wrap items-center gap-3">
          <select
            value={selectedId}
            onChange={(e) => setSelectedId(e.target.value)}
            className="bg-slate-900 border border-slate-700 text-xs font-bold text-white rounded-xl px-3 py-2.5"
          >
            {Object.values(startups).map((s) => (
              <option key={s.startup.id} value={s.startup.id}>
                {s.startup.name}
              </option>
            ))}
          </select>

          <button
            onClick={handleExportPDF}
            disabled={exporting}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white text-xs font-bold transition-all shadow-lg shadow-indigo-600/25"
          >
            <Printer className="w-4 h-4" />
            <span>Export PDF (Print)</span>
          </button>

          <button
            onClick={handleExportDOCX}
            disabled={exporting}
            className="flex items-center gap-2 px-4 py-2.5 rounded-xl bg-slate-900 border border-slate-700 hover:border-indigo-500/40 text-slate-200 text-xs font-bold transition-all"
          >
            <Download className="w-4 h-4 text-indigo-400" />
            <span>Export Text / DOCX</span>
          </button>

          <button
            onClick={handleShare}
            className="flex items-center gap-2 px-3.5 py-2.5 rounded-xl bg-slate-900 border border-slate-700 text-slate-200 text-xs font-bold transition-all"
          >
            <Share2 className="w-4 h-4 text-cyan-400" />
            <span>{shared ? 'Link Copied!' : 'Share'}</span>
          </button>
        </div>
      </div>

      {/* Printable Executive Document Card */}
      <div className="p-8 sm:p-12 rounded-2xl bg-slate-900/80 border border-slate-800 shadow-2xl backdrop-blur-xl space-y-8 print:border-none print:shadow-none print:bg-white print:text-black">
        {/* Document Header */}
        <div className="flex items-center justify-between border-b border-slate-800 print:border-black/20 pb-6">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-600 flex items-center justify-center text-white font-extrabold text-lg">
              IQ
            </div>
            <div>
              <h2 className="text-2xl font-black text-white print:text-black">{startup.name}</h2>
              <p className="text-xs text-indigo-400 print:text-indigo-700 font-semibold">{startup.tagline}</p>
            </div>
          </div>

          <div className="text-right">
            <span className="text-[10px] uppercase font-bold text-slate-400 print:text-gray-500 block">StartupIQ Validation Rating</span>
            <span className="text-3xl font-black text-emerald-400 print:text-emerald-700">
              {analysis.validationScore} / 100
            </span>
          </div>
        </div>

        {/* 1. Executive Summary */}
        <div className="space-y-2">
          <h3 className="text-sm font-bold text-white print:text-black uppercase tracking-wider">
            1. Executive Summary
          </h3>
          <p className="text-xs text-slate-300 print:text-gray-800 leading-relaxed bg-slate-950/60 print:bg-gray-100 p-4 rounded-xl">
            {analysis.summary}
          </p>
        </div>

        {/* 2. Problem & Solution */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
          <div className="p-4 rounded-xl bg-slate-950/60 print:bg-gray-50 border border-slate-800 print:border-gray-200 space-y-1">
            <span className="font-bold text-rose-400 print:text-rose-700 block uppercase text-[10px]">Identified Problem</span>
            <p className="text-slate-300 print:text-gray-800">{startup.problem}</p>
          </div>

          <div className="p-4 rounded-xl bg-slate-950/60 print:bg-gray-50 border border-slate-800 print:border-gray-200 space-y-1">
            <span className="font-bold text-indigo-400 print:text-indigo-700 block uppercase text-[10px]">Proprietary Solution</span>
            <p className="text-slate-300 print:text-gray-800">{startup.solution}</p>
          </div>
        </div>

        {/* 3. Market Sizing */}
        <div className="p-4 rounded-xl bg-slate-950/60 print:bg-gray-50 border border-slate-800 print:border-gray-200 space-y-2 text-xs">
          <span className="font-bold text-white print:text-black block uppercase text-[10px]">3. Market Sizing (TAM / SAM / SOM)</span>
          <div className="grid grid-cols-3 gap-4 text-center">
            <div>
              <span className="text-slate-400 text-[10px] block">TAM</span>
              <span className="font-bold text-white print:text-black">{market.tam}</span>
            </div>
            <div>
              <span className="text-slate-400 text-[10px] block">SAM</span>
              <span className="font-bold text-white print:text-black">{market.sam}</span>
            </div>
            <div>
              <span className="text-slate-400 text-[10px] block">SOM</span>
              <span className="font-bold text-indigo-400 print:text-indigo-700">{market.som}</span>
            </div>
          </div>
        </div>

        {/* 4. Critical Risk Telemetry */}
        <div className="space-y-2 text-xs">
          <span className="font-bold text-white print:text-black block uppercase text-[10px]">4. AI Devil&apos;s Advocate Critical Risks</span>
          <div className="space-y-2">
            {analysis.risks.slice(0, 3).map((rk) => (
              <div key={rk.id} className="p-3 rounded-lg bg-slate-950/40 print:bg-gray-50 border border-slate-800 print:border-gray-200">
                <p className="font-bold text-rose-300 print:text-rose-700">[{rk.severity}] {rk.title}</p>
                <p className="text-slate-400 print:text-gray-700 text-[11px] mt-0.5">{rk.explanation}</p>
              </div>
            ))}
          </div>
        </div>

        {/* 5. Financial Projections Summary */}
        <div className="p-4 rounded-xl bg-slate-950/60 print:bg-gray-50 border border-slate-800 print:border-gray-200 text-xs space-y-2">
          <span className="font-bold text-white print:text-black block uppercase text-[10px]">5. Financial Performance Summary</span>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div>
              <span className="text-slate-400 text-[10px] block">Monthly Revenue</span>
              <span className="font-bold text-emerald-400 print:text-emerald-700">{financials.monthlyRevenue}</span>
            </div>
            <div>
              <span className="text-slate-400 text-[10px] block">Monthly Expenses</span>
              <span className="font-bold text-slate-300 print:text-gray-800">{financials.monthlyExpenses}</span>
            </div>
            <div>
              <span className="text-slate-400 text-[10px] block">Break-Even Threshold</span>
              <span className="font-bold text-indigo-400 print:text-indigo-700">{financials.breakEvenCustomers} Customers</span>
            </div>
            <div>
              <span className="text-slate-400 text-[10px] block">Runway</span>
              <span className="font-bold text-amber-400 print:text-amber-700">{financials.runwayMonths} Months</span>
            </div>
          </div>
        </div>

        {/* Document Footer */}
        <div className="pt-6 border-t border-slate-800 print:border-gray-300 flex items-center justify-between text-[11px] text-slate-500 print:text-gray-600">
          <span>StartupIQ Intelligence Dossier • ID: {startup.id}</span>
          <div className="flex items-center gap-1 text-emerald-400 print:text-emerald-700 font-semibold">
            <ShieldCheck className="w-3.5 h-3.5" />
            <span>Verified AI Co-Founder Seal</span>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function ReportsPage() {
  return (
    <Suspense fallback={
      <div className="max-w-5xl mx-auto px-4 py-12 flex items-center justify-center min-h-[60vh]">
        <div className="text-center space-y-3">
          <div className="w-10 h-10 rounded-full border-2 border-indigo-500 border-t-transparent animate-spin mx-auto" />
          <p className="text-slate-400 text-sm">Loading Report...</p>
        </div>
      </div>
    }>
      <ReportsContent />
    </Suspense>
  );
}
